### ISSUE TITLE
Separate generator from decode/encode.

### ISSUE THREAD

**Issue by jimmyaxod** [loopholelabs/polyglot-ts#7]
Including polyglot-ts adds around 5MB due to pulling in the protobuf libs etc.
Need to separate out the generator from the encode/decode. Encode/decode should be kept as small as possible for use eg in wasm modules.

**Comment by jimmyaxod** [comment]
Fixed in 0.4.0 release

**Comment by pojntfx** [comment]
Resolved in #8
